#!/usr/bin/env sh

state="$(xrandr | grep connected | awk '{print $1 " " $2}')"

if echo "$state" | grep -q "DP-1-3 connected" &&
   echo "$state" | grep -q "eDP-1 connected" &&
   echo "$state" | grep -q "DP-1-2 connected"; then
    printf 'Using docked screen layout\n'
    xrandr \
        --output eDP-1  --primary --mode 1920x1200 --pos 0x0 --rotate normal \
        --output HDMI-1 --off \
        --output DP-1   --off \
        --output DP-2   --off \
        --output DP-3   --off \
        --output DP-4   --off \
        --output DP-1-1 --off \
        --output DP-1-2 --mode 1920x1200 --pos 1920x0 --rotate normal \
        --output DP-1-3 --mode 1920x1200 --pos 3840x0 --rotate left
elif echo "$state" | grep -q "HDMI-1 connected" &&
     echo "$state" | grep -q "eDP-1 connected"; then
    printf 'Using presenter screen layout\n'
    xrandr \
        --output eDP-1  --primary --mode 1920x1200 --pos 0x0 --rotate normal \
        --output HDMI-1 --mode 1920x1200 --pos 1920x0 --rotate normal \
        --output DP-1   --off \
        --output DP-2   --off \
        --output DP-3   --off \
        --output DP-4   --off \
        --output DP-1-1 --off \
        --output DP-1-2 --off \
        --output DP-1-3 --off
elif echo "$state" | grep -q "eDP-1 connected"; then
    printf 'Using single screen layout\n'
    xrandr \
        --output eDP-1  --primary --mode 1920x1200 --pos 0x0 --rotate normal \
        --output HDMI-1 --off \
        --output DP-1   --off \
        --output DP-2   --off \
        --output DP-3   --off \
        --output DP-4   --off \
        --output DP-1-1 --off \
        --output DP-1-2 --off \
        --output DP-1-3 --off
else
    printf 'Unknown screen layout\n'
fi
