#!/usr/bin/env sh

LAST_STATE_FILE=/tmp/sconnect_last_state
URL="https://software.siemens.dk"
TIMEOUT=5

curl --connect-timeout $TIMEOUT $URL
CURL_EXIT_CODE=$?

if [ -f "$LAST_STATE_FILE" ]; then
  LAST_STATE=$(cat "$LAST_STATE_FILE")
else
  LAST_STATE=127
fi

if [ $CURL_EXIT_CODE -ne 0 ] && [ "$LAST_STATE" -eq 0 ]; then
  notify-send "SConnect loop" "Connection to $URL failed."
elif [ $CURL_EXIT_CODE -eq 0 ] && [ "$LAST_STATE" -ne 0 ]; then
  notify-send "SConnect loop" "Connection to $URL succeeded."
fi

echo $CURL_EXIT_CODE >$LAST_STATE_FILE
