name: Nix Format Check

on: [push, pull_request]

jobs:
  check-format:
    name: Check Nix files format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Check Nix files formatting
      run: nix-shell -p nixfmt-classic gnumake checkmake shellharden ormolu --run "make lint"
