name: Nix Format Check

on: [push, pull_request]

jobs:
  check-format:
    name: Check Nix files format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v16
      with:
        install_options: '--no-daemon'

    - name: Install nixfmt
      run: |
        nix-channel --add https://nixos.org/channels/nixos-unstable nixos
        nix-channel --update
        nix-env -iA nixos.nixpkgs-fmt

    - name: Check Nix files formatting
      run:  nixpkgs-fmt --check .
